(lang dune 3.21)

(name hackvmt)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation  https://url/to/documentation)

(package
 (name hackvmt)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
  (ocaml (>= 5.5.0))
  (dune (>= 3.0))
  (base (>= 0.17))
  (stdio (>= 0.17))
  (ppx_jane (>= 0.17))
  )
  
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
